name: Snyk
on: [pull_request] # TODO: switch to master branch
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@eeb10cff27034e7acf239c5d29f62154018672fd # tag=v3
      - name: Prepare snyk
        run: |
          npm run setup:snyk
          npm ci
          yarn install --no-immutable --mode=skip-build
      - name: Snyk Monitor
        continue-on-error: true
        # if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk monitor --dev --yarn-workspaces --prune-repeated-subdependencies --exclude packages/samples
      - name: Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk test --dev --yarn-workspaces --sarif-file-output=./sarifs/snyk.sarif --prune-repeated-subdependencies --exclude packages/samples
      - name: Snyk Code
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk code test --dev --all-projects --sarif > ./sarifs/snyk-code.sarif --prune-repeated-subdependencies --exclude packages/samples
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@e41f8baf4a726fae01b76b1337c600136468896e # tag=v1
        with:
          sarif_file: ./sarifs
