name: Snyk
on:
  push:
    branches:
      - master
  pull_request:
  workflow_run:
    workflows:
      - Master Robot
      - Manual package creation
    types:
      - completed
jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - uses: actions/setup-node@2fddd8803e2f5c9604345a0b591c3020ee971a93 # tag=v3
      - name: Prepare snyk
        run: |
          npm ci
          yarn install --no-immutable --mode=skip-build
          npm run setup:snyk
      - name: Snyk Monitor
        continue-on-error: true
        if: ${{ github.event_name != 'pull_request' }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk monitor --yarn-workspaces
      - name: Snyk Test
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk test --yarn-workspaces --sarif-file-output=./sarifs/snyk.sarif
      - name: Snyk Code
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          NODE_OPTIONS: --max-old-space-size=8192
        run: npx snyk code test --all-projects --sarif > ./sarifs/snyk-code.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@a34ca99b4610d924e04c68db79e503e1f79f9f02 # v2
        with:
          sarif_file: ./sarifs
